site_name: Web de Lara
site_url: https://a24pemola.github.io/a24pemola
theme:
  name: material

nav:
  - Inicio: index.md
  - Ejercicios:
      - "Ejercicio 1": https://github.com/a24pemola/DespliegueWeb/blob/main/Actividad%202.1/practica2_1.md

      
