site_name: Web de Lara
site_url: https://a24pemola.github.io/

theme:
  name: material

nav:
  - Home: index.md
  - DAW:
    - UD2:
      - Ejercicio 2.1: actividad_2.1/index.md
      - Ejercicio 2.2: actividad_2.2/index.md
      - Ejercicio 2.3: actividad_2.3/index.md
      - Ejercicio 2.4: actividad_2.4/index.md
      - Ejercicio 2.5: actividad_2.5/index.md
    - UD3:
      - Ejercicio 3.1: actividad_3.1/index.md
      - Ejercicio 3.2: actividad_3.2/index.md
      - Ejercicio 3.3: actividad_3.3/index.md
      - Ejercicio 3.4: actividad_3.4/index.md
    - Extra:
      - Ampliación: ampliacion/index.md
    - UD4:
      - Ejercicio 4.1: actividad_4.1/index.md
    - UD5:
      - Ejercicio Git I: actividad_git1/index.md
      - Ejercicio Git II: actividad_git2/index.md
    - UD6:
      - Ejercicio 6.1: actividad_6.1/index.md
